INSERT INTO task(section_id, start_date, completed,  due_date, description )
VALUES
(14, now() - '1 days' :: INTERVAL, false, now() + '12 days' :: INTERVAL, 'user should be able to log in'),
(15, now() - '1 days' :: INTERVAL, false, now() + '12 days' :: INTERVAL, 'user should be able to log in'),
(16, now() - '1 days' :: INTERVAL, false, now() + '4 days' :: INTERVAL, 'user should be able to log in'),
(17, now() - '1 days' :: INTERVAL, false, now() + '62 days' :: INTERVAL, 'user should be able to log in'),
(18, now() - '1 days' :: INTERVAL, false, now() + '9 days' :: INTERVAL, 'user should be able to log in'),
(19, now() - '1 days' :: INTERVAL, false, now() + '9 days' :: INTERVAL, 'user should be able to log in'),
(20, now() - '1 days' :: INTERVAL, false, now() + '22 days' :: INTERVAL, 'user should be able to log in'),
(21, now() - '1 days' :: INTERVAL, false, now() + '7 days' :: INTERVAL, 'user should be able to log in'),
(22, now() - '1 days' :: INTERVAL, false, now() + '2 days' :: INTERVAL, 'user should be able to log in'),
(23, now() - '1 days' :: INTERVAL, false, now() + '1 days' :: INTERVAL, 'user should be able to log in'),
(24, now() - '1 days' :: INTERVAL, false, now() + '5 days' :: INTERVAL, 'user should be able to log in'),
(25, now() - '1 days' :: INTERVAL, false, now() + '1 days' :: INTERVAL, 'user should be able to log in'),
(26, now() - '1 days' :: INTERVAL, false, now() + '13 days' :: INTERVAL, 'user should be able to log in'),
(14, now() - '1 days' :: INTERVAL, false, now() + '12 days' :: INTERVAL, 'user should be able to log in'),
(14, now() - '13 days' :: INTERVAL, true, now() - '2 days' :: INTERVAL, 'user should be able to log in'),
(15, now() - '14 days' :: INTERVAL, false, now() + '15 days' :: INTERVAL, 'user should be able to log in'),
(16, now() - '75 days' :: INTERVAL, true, now() - '13 days' :: INTERVAL, 'user should be able to log in'),
(14, now() - '14 days' :: INTERVAL, false, now() + '2 days' :: INTERVAL, 'user should be able to log in'),
(15, now() - '13 days' :: INTERVAL, true, now() - '2 days' :: INTERVAL, 'user should be able to log in')