INSERT INTO task(section_id, start_date, completed,  due_date, description )
VALUES
(1, now() - '1 days' :: INTERVAL, false, now() + '12 days' :: INTERVAL, 'user should be able to log in'),
(1, now() - '1 days' :: INTERVAL, false, now() + '12 days' :: INTERVAL, 'user should be able to log in'),
(2, now() - '1 days' :: INTERVAL, false, now() + '4 days' :: INTERVAL, 'user should be able to log in'),
(3, now() - '1 days' :: INTERVAL, false, now() + '62 days' :: INTERVAL, 'user should be able to log in'),
(4, now() - '1 days' :: INTERVAL, false, now() + '9 days' :: INTERVAL, 'user should be able to log in'),
(5, now() - '1 days' :: INTERVAL, false, now() + '9 days' :: INTERVAL, 'user should be able to log in'),
(6, now() - '1 days' :: INTERVAL, false, now() + '22 days' :: INTERVAL, 'user should be able to log in'),
(7, now() - '1 days' :: INTERVAL, false, now() + '7 days' :: INTERVAL, 'user should be able to log in'),
(8, now() - '1 days' :: INTERVAL, false, now() + '2 days' :: INTERVAL, 'user should be able to log in'),
(9, now() - '1 days' :: INTERVAL, false, now() + '1 days' :: INTERVAL, 'user should be able to log in'),
(10, now() - '1 days' :: INTERVAL, false, now() + '5 days' :: INTERVAL, 'user should be able to log in'),
(11, now() - '1 days' :: INTERVAL, false, now() + '1 days' :: INTERVAL, 'user should be able to log in'),
(12, now() - '1 days' :: INTERVAL, false, now() + '13 days' :: INTERVAL, 'user should be able to log in'),
(13, now() - '1 days' :: INTERVAL, false, now() + '12 days' :: INTERVAL, 'user should be able to log in'),
(1, now() - '13 days' :: INTERVAL, true, now() - '2 days' :: INTERVAL, 'user should be able to log in'),
(11, now() - '14 days' :: INTERVAL, false, now() + '15 days' :: INTERVAL, 'user should be able to log in'),
(12, now() - '75 days' :: INTERVAL, true, now() - '13 days' :: INTERVAL, 'user should be able to log in'),
(13, now() - '14 days' :: INTERVAL, false, now() + '2 days' :: INTERVAL, 'user should be able to log in'),
(1, now() - '13 days' :: INTERVAL, true, now() - '2 days' :: INTERVAL, 'user should be able to log in')